apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-script-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-script
  template:
    metadata:
      labels:
        app: stats-script
    spec:
      containers:
      - name: stats-script
        image: fineken/stats-script:latest
