apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app2
  template:
    metadata:
      labels:
        app: web-app2
    spec:
      containers:
      - name: web-app2
        image: fineken/web-app:latest
        ports:
        - containerPort: 5000
